site_name: MHIM Handbook 
site_url: https://www.mhimhandbook.com

Copyright: 
All materials used in this book are appropriately referenced. 

nav:
  - Home: index.md
  - docs_dir: 'docs' 
  - Cardiovascular Medicine: Cardiovascular Medicine.md
  - Endocrinology and Metabolism: Endocrinology and Metabolism.md 
  - Gastroenterology: Gastroenterology.md
  - General Internal Medicine: General Internal Medicine.md 
  - Hematology: Hematology.md 
  - Infectious disease: Infectious Disease.md 
  - Neurology: Neurology.md
  - Oncology: Oncology.md 
  - Pulmonary and Critical Medicine: Pulmonary and Critical Care Medicine.md 
  - Rheumatology: Rheumatology.md 

theme: 
  name: material

palette:
 - scheme: default
  primary: black
  accent: amber
  toggle:
    icon: material/toggle-switch-off-outline
    name: Switch to dark mode
